feature: microservice generator
kumparan/fer pull request #1
Opened 2019-09-30 04:15 UTC by fajrifernanda

2019-10-02 03:27 UTC, zhenqianz commented on .chglog/config.yml
> +style: gitlab
github

2019-10-02 03:29 UTC, zhenqianz commented on cmd/root.go
> +	Use:   "cobra-example",
fer

2019-10-02 03:29 UTC, zhenqianz commented on cmd/root.go
> +	Long: `This application shows how to create modern CLI
ini dibenerin ya

2019-10-02 03:30 UTC, zhenqianz commented on generator/main_generator.go
> +	fmt.Print("Enter proto path (Ex:\"pb/content/content.proto\"): ")
langsung di flag nya aja, kalo ga ada flag nya bikin error aja

2019-10-02 03:31 UTC, zhenqianz commented on generator/main_generator.go
> +git remote add origin "git@gitlab.kumparan.com:yowez/$servicename.git";
git nya ga usah

2019-10-03 08:01 UTC, zhenqianz requested changes

2019-10-03 08:01 UTC, zhenqianz commented on generator/main_generator.go
> +		g.cleaningWhenError("fail create client folder inside "+serviceName)
cleaningWhenError diganti namanya. rollbackWhenError aja

2019-10-03 08:01 UTC, zhenqianz commented on cmd/project.go
> +	name, _ := cmd.Flags().GetString("name")
ini err nya dicek aja, dan distop kerjaannya kalo ada error

2019-10-03 08:15 UTC, zhenqianz approved these changes

2019-10-03 08:18 UTC, ivanp commented on console/project.go
> +	if err!=nil{
Ini udah dilewatin gofmt/linter?

2019-10-03 08:22 UTC, fajrifernanda commented on console/project.go
> +	if err!=nil{
updated @ivanp

2019-10-07 03:30 UTC, merged