feature: created cli command to install change-log
kumparan/fer pull request #2
Opened 2019-10-01 10:10 UTC by bambangDeny

2019-10-01 10:14 UTC, zhenqianz commented on cmd/install.go
> +func chglog(cmd *cobra.Command, args []string) error {
apa ini

2019-10-01 10:14 UTC, zhenqianz commented on cmd/list.go
> +func init() {
iya, execute iya

2019-10-01 10:14 UTC, zhenqianz commented on cmd/list.go
> +var listCmd = &cobra.Command{
iya, RootCmd iya

2019-10-01 11:29 UTC, zhenqianz requested changes

2019-10-01 11:29 UTC, zhenqianz commented on cmd/install.go
> +var installChgLogCmd = &cobra.Command{
ini kenapa dipisah, 1 command aja fer install, install semua yang dibutuhin oleh si fer

2019-10-01 11:29 UTC, zhenqianz commented on cmd/install.go
> +	repository.InstalltheChangelog()
Install changelog, ga perlu the nya.

2019-10-01 11:29 UTC, zhenqianz commented on cmd/install.go
> +	repository.CheckExistenceOfGolang()
kenapa namanya repository?

2019-10-01 11:29 UTC, zhenqianz commented on cmd/list.go
> +var listCmd = &cobra.Command{
nah ini masih sama

2019-10-01 14:51 UTC, bambangDeny commented on cmd/install.go
> +var installChgLogCmd = &cobra.Command{
ini gue gak tau sampe bates apa aja kebutuhan si fer? itu dibuat gitu biar installnya sesuai kebutuhan aja sih dja

2019-10-01 15:01 UTC, bambangDeny commented on cmd/install.go
> +	repository.CheckExistenceOfGolang()
hmm gue gak tau cara menentukan naming convention dja, apa controller, utils, repository, helper. gimana cara nentuin nama yg benar gitu sih

2019-10-03 04:21 UTC, ivanp commented on installer/helper.go
> +		fmt.Println("Go version must be 1.12.7 or latest")
Di config

2019-10-03 04:22 UTC, ivanp commented on installer/watchmedo_installer.go
> +			fmt.Println("you must install python first")
fmt.Println("you must install python-pip first")

2019-10-03 04:22 UTC, ivanp commented on cmd/root.go
> +	Use:   "cobra-example",
Jangan lupa ganti.

2019-10-07 11:49 UTC, ivanp commented on installer/helper.go
> +	v1, _ := version.NewVersion(config.GoVersion)
Errornya jangan dikacangin.

2019-10-07 11:51 UTC, ivanp commented on installer/protobuf_installer.go
> +		cmdUnzipToBinProtocPath := exec.Command("unzip", "-o", filePath, "-d", tmp, "bin/protoc")
Pakai library archive aja.

2019-10-08 08:01 UTC, zhenqianz approved these changes

2019-10-08 08:01 UTC, merged