Feature/ban 2984 fer check latest version
kumparan/fer pull request #8
Opened 2019-10-18 10:49 UTC by bambangDeny

2019-10-18 11:48 UTC, fajrifernanda approved these changes

2019-10-21 04:32 UTC, zhenqianz requested changes

2019-10-21 04:32 UTC, zhenqianz commented on console/version.go
> +func getGithubReleaseLatest() (string) {
getLatestRelease aja, ga perlu pake github

2019-10-21 04:32 UTC, zhenqianz commented on console/version.go
> +type githubRelease struct {
ini apa ya?

2019-10-21 04:32 UTC, zhenqianz commented on config/default.go
> +	APIFerGithubReleaseURL = "https://api.github.com/repos/kumparan/fer/releases"
ReleaseURL aja

2019-10-21 04:32 UTC, zhenqianz commented on console/version.go
> +	var jsonData []githubRelease
apa nih jsonData

2019-10-21 04:32 UTC, zhenqianz commented on console/version.go
> +		fmt.Println("your fer is out of date, please updated your fer")
ini ganti copy nya ya.
"Newer version of fer is available!! Update to the latest version to get the new features and bugfixes."

2019-10-21 08:07 UTC, bambangDeny commented on console/version.go
> +type githubRelease struct {
ini struct buat json dr api github release

2019-11-08 07:15 UTC, zhenqianz commented on config/default.go
> +	ConfigDir = ".config/fer"
ini ga mau pake filepath join?

2019-11-14 04:25 UTC, zhenqianz approved these changes

2019-11-14 04:25 UTC, merged